### ISSUE TITLE
Label Speaker Pics

### ISSUE THREAD

**Issue by TobiasPSP** [PowerShellConferenceEU/PowerShellConferenceEU.github.io#94] opened 2017-02-17 12:06 UTC
Ryan suggested highlighting some speakers. That's a good idea.
What if we added a symbol or a text label for Microsoft employees and for active MVPs?
I would not think we should order the speakers by these labels but highlighting their special status would be awesome and illustrate how many of these are actually speaking.

**Comment by amandadebler** [comment] 2017-02-17 15:24
Maybe a little square Microsoft logo, like we did the flags for speaker sessions?

**Comment by amandadebler** [comment] 2017-02-17 15:38
Cut the logo down to various sizes and added to Dev branch (16x16, 24x24, and 32x32, as well as full size original)

**Comment by amandadebler** [comment] 2017-03-13 21:06
@PowerShellConferenceEU/owners  Do we still want to do this?

**Comment by stuartpreston** [comment] 2019-10-14 13:06
Closing this due to age. We'll definitely consider highlighting some of the early speakers that are confirmed this year.

**Closed by stuartpreston** 2019-10-14 13:06 UTC
